 
# @name createAsset
POST {{host}}/assets
Content-Type: application/json

{
    "name": "Nvdia",
    "symbol": "NVDA",
    "price": 100,
    "image": "NVDA.png"
}
###

@assetId = {{ createAsset.response.body._id }}
###

GET {{host}}/assets
###

GET {{host}}/assets/NVDA
###


GET {{host}}/assets/NVDA/dailies

###

# @name createWallet
POST {{host}}/wallets
Content-Type: application/json
###

@walletId = {{ createWallet.response.body._id }}

GET {{host}}/wallets
###

GET {{host}}/wallets/{{ walletId }}
###

# @name createWalletAsset

POST {{host}}/wallets/{{walletId}}/assets
Content-Type: application/json

{
    "assetId": "{{assetId}}",
    "shares": 10
}

###

# @name createOrder

POST {{host}}/orders
Content-Type: application/json

{
    "walletId": "{{walletId}}",
    "assetId": "{{assetId}}",
    "shares": 20,
    "price": 120,
    "type": "BUY"
}

###

GET {{host}}/orders?walletId={{walletId}}

###

#  Assets Dailies

POST {{host}}/assets/NVDA/dailies
Content-Type: application/json

{
    "date" : "2021-12-12",
    "price" : 121
}

###

GET {{host}}/assets/NVDA/dailies

###