 
# @name createAsset
POST {{host}}/assets
Content-Type: application/json

{
    "name": "Nvdia",
    "symbol": "NVDA",
    "price": 1000,
    "image": "NVDA.png"
}
###

@assetId = {{ createAsset.response.body._id }}
###

GET {{host}}/assets
###

GET {{host}}/assets/NVDA
###

###

# @name createWallet
POST {{host}}/wallets
Content-Type: application/json
###

@walletId = {{ createWallet.response.body._id }}

GET {{host}}/wallets
###

GET {{host}}/wallets/{{ walletId }}
###

# @name createWalletAsset

POST {{host}}/wallets/{{walletId}}/assets
Content-Type: application/json

{
    "assetId": "{{assetId}}",
    "shares": 10
}

###

# @name createOrder

POST {{host}}/orders
Content-Type: application/json

{
    "walletId": "{{walletId}}",
    "assetId": "{{assetId}}",
    "shares": 50,
    "price": 194,
    "type": "BUY"
}

###

GET {{host}}/orders?walletId={{walletId}}