 
# @name createAsset
POST {{host}}/assets
Content-Type: application/json

{
    "name": "Amazon1",
    "symbol": "A1",
    "price": 100,
    "image": "AMZN.png"
}
###

@assetId = {{ createAsset.response.body._id }}
###

GET {{host}}/assets
###

GET {{host}}/assets/A1
###

###

# @name createWallet
POST {{host}}/wallets
Content-Type: application/json
###

@walletId = {{ createWallet.response.body._id }}

GET {{host}}/wallets
###

GET {{host}}/wallets/{{ walletId }}
###

# @name createWalletAsset

POST {{host}}/wallets/{{walletId}}/assets
Content-Type: application/json

{
    "assetId": "{{assetId}}",
    "shares": 100
}

###

# @name createOrder

POST {{host}}/orders
Content-Type: application/json

{
    "walletId": "{{walletId}}",
    "assetId": "{{assetId}}",
    "shares": 10,
    "price": 100,
    "type": "BUY"
}

###

GET {{host}}/orders?walletId={{walletId}}